spring:
  application.name: cryptocurrency-exchange
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
      port: 8082

service:
  supported-currencies: [BTC, LTC, ETH, BCH, XRP, TRX, DAI, DOGE, BNB, USDT, KRW, SAR, USDC]
  synchronization-rate: 10000
  fee: 0.01
  min-amount: 0.0000100
  max-amount: 1000000.0
  expiration-factor: 1
  coin-gate-endpoint: "https://api.coingate.com/v2/rates/merchant"